name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Deploy to HP Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 100.113.51.13
          username: antony
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e

            cd /home/antony/Applications/homelab-frontend

            git pull origin main

            docker compose up -d --build

            docker compose ps
